Repository google/amber, pull requests merged in 2018-12, with the labels that each got.

#135 Provide features and extensions to engine initialization
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/script.h
  src/vkscript/executor_test.cc
  src/vkscript/nodes.cc
  src/vkscript/nodes.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#136 Move commands into parent script object.
  src/script.h
  src/vkscript/executor.cc
  src/vkscript/nodes.cc
  src/vkscript/nodes.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vkscript/script.cc
  src/vkscript/script.h
Labels: refactoring

#137 Extend engine configuration options.
  include/amber/amber.h
  include/amber/amber_dawn.h
  include/amber/amber_vulkan.h
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/vkscript/executor_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: enhancement, refactoring

#138 Allow host to provide a shader map.
  include/amber/amber.h
  src/amber.cc
  src/amberscript/executor.cc
  src/amberscript/executor.h
  src/executor.h
  src/shader_compiler.cc
  src/shader_compiler.h
  src/shader_compiler_test.cc
  src/vkscript/executor.cc
  src/vkscript/executor.h
  src/vkscript/executor_test.cc
Labels: enhancement

#140 Create an EngineData structure.
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/script.h
  src/vkscript/executor.cc
  src/vkscript/executor_test.cc
  src/vkscript/nodes.cc
  src/vkscript/nodes.h
  src/vkscript/parser.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#146 Implement GetShaderInfo.
  src/CMakeLists.txt
  src/script.cc
  src/script.h
  src/script_test.cc
Labels: enhancement

#144 Make spirv-tools, googletest and shaderc build optional
  CMakeLists.txt
  README.md
  samples/CMakeLists.txt
  samples/amber.cc
  src/CMakeLists.txt
  src/shader_compiler.cc
  src/shader_compiler_test.cc
  src/vkscript/executor_test.cc
  third_party/Android.mk
  third_party/CMakeLists.txt
  tools/update_build_version.py
Labels: enhancement, infra

#157 Remove IndicesNode and use Buffer directly
  src/script.h
  src/vkscript/executor.cc
  src/vkscript/nodes.cc
  src/vkscript/nodes.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vkscript/script.cc
  src/vkscript/script.h
Labels: refactoring

#164 Convert Vertex data into a buffer.
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/amberscript/script_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/vkscript/executor.cc
  src/vkscript/nodes.cc
  src/vkscript/nodes.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vkscript/script.cc
  src/vkscript/script.h
Labels: refactoring

#166 Fix run-lint on mac
  tools/run-lint.sh
Labels: infra

#167 Output any errors produced during test runs.
  tests/run_tests.py
Labels: bug

#168 Remove Requirement nodes and use buffers for frame and depth buffers
  Android.mk
  src/CMakeLists.txt
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/vkscript/executor.cc
  src/vkscript/executor_test.cc
  src/vkscript/nodes.cc
  src/vkscript/nodes.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vkscript/script.cc
  src/vkscript/script.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#170 Merge scripts and executors.
  Android.mk
  src/CMakeLists.txt
  src/amber.cc
  src/amberscript/executor.cc
  src/amberscript/executor.h
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/amberscript/script.cc
  src/amberscript/script.h
  src/amberscript/script_test.cc
  src/engine.h
  src/executor.cc
  src/executor.h
  src/executor_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
  src/script.cc
  src/script.h
  src/script_test.cc
  src/vkscript/executor.cc
  src/vkscript/executor.h
  src/vkscript/parser.cc
  src/vkscript/parser.h
  src/vkscript/parser_test.cc
  src/vkscript/script.cc
  src/vkscript/script.h
Labels: refactoring

#171 Count line numbers in VkScript
  src/amberscript/parser_test.cc
  src/tokenizer.h
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  src/vkscript/command_parser_test.cc
  src/vkscript/parser.cc
  src/vkscript/parser.h
  src/vkscript/parser_test.cc
  src/vkscript/section_parser.cc
  src/vkscript/section_parser.h
Labels: enhancement

#175 Output token on VkScript parse error
  src/tokenizer.cc
  src/tokenizer.h
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
Labels: enhancement

#176 Fix warnings on newer clang
  src/executor_test.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/pipeline.cc
Labels: bug

#181 Vulkan: fix compile and test failures
  src/vulkan/engine_vulkan.cc
Labels: bug

#182 Docs
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/buffer.h
  src/engine.h
  src/executor.h
  src/feature.h
  src/format.h
  src/parser.cc
  src/parser.h
  src/script.h
  src/shader.h
  src/verifier.h
  src/vkscript/parser.cc
  src/vkscript/parser.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
Labels: documentation

#172 [ndk-build] Only build a single platform.
  android_test/jni/Application.mk
Labels: infra

#196 Fix: compiler error
  src/vulkan/resource.cc
Labels: bug
