Repository google/amber, pull requests merged in 2019-02, with the labels that each got.

#262 Fixes for OSX build
  README.md
  src/vulkan/vertex_buffer_test.cc
Labels: bug, documentation

#263 [vulkan] Inline setting data into vertex buffer.
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
Labels: refactoring

#265 Remove unused file
  src/vulkan/bit_copy.cc
Labels: refactoring

#264 Add test case for parsing line number bug.
  src/vkscript/parser_test.cc
Labels: bug

#256 [amberscript] Parse PIPELINE BIND calls for color and depth buffers
  CMakeLists.txt
  docs/amber_script.md
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: enhancement

#266 [vulkan] Always require vulkan to be provided to library.
  include/amber/amber_vulkan.h
  src/vulkan/CMakeLists.txt
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/log.cc
  src/vulkan/log.h
  src/vulkan/vk-funcs.inc
Labels: refactoring

#273 Allow setting SPIR-V target environment.
  DEPS
  include/amber/amber.h
  samples/amber.cc
  src/amber.cc
  src/executor.cc
  src/script.h
  src/shader_compiler.cc
  src/shader_compiler.h
Labels: enhancement

#271 Parse VERTEX_DATA and INDEX_DATA.
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/pipeline.cc
  src/pipeline.h
Labels: enhancement

#274 Sample app shutdown always
  samples/amber.cc
Labels: bug

#276 [vulkan] Split vulkan/command file.
  src/vulkan/CMakeLists.txt
  src/vulkan/command_buffer.cc
  src/vulkan/command_buffer.h
  src/vulkan/command_pool.cc
  src/vulkan/command_pool.h
  src/vulkan/engine_vulkan.h
  src/vulkan/pipeline.h
Labels: refactoring

#281 [amberscript] Parse generic buffer bindings.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_test.cc
  src/buffer.h
  src/buffer_data.h
  src/pipeline.cc
  src/pipeline.h
Labels: enhancement

#268 Vkscript: fix matrix stride bug
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  tests/cases/compute_mat2x2.amber
  tests/cases/compute_mat2x3.amber
  tests/cases/compute_mat3x2.amber
  tests/cases/compute_mat3x3.amber
  tests/cases/compute_mat3x4.amber
  tests/cases/compute_mat4x3.amber
  tests/cases/compute_probe_mat3.amber
  tests/cases/compute_push_const_mat2x2.amber
  tests/cases/compute_push_const_mat2x3.amber
  tests/cases/compute_push_const_mat3x2.amber
  tests/cases/compute_push_const_mat3x3.amber
  tests/cases/compute_push_const_mat3x4.amber
  tests/cases/compute_push_const_mat4x3.amber
Labels: bug

#283 [vkscript] Validate offsets for uniform and ssbo commands.
  docs/vk_script.md
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
Labels: bug

#284 Generate default pipeline in VkScript.
  src/executor_test.cc
  src/pipeline.cc
  src/vkscript/parser.cc
  src/vkscript/parser.h
  src/vkscript/parser_test.cc
  src/vkscript/section_parser.h
Labels: refactoring

#286 Execute from pipeline, not script.
  src/executor.cc
  src/pipeline.cc
  src/pipeline.h
  src/shader_compiler.cc
  src/shader_compiler.h
Labels: refactoring

#289 Move pipeline setup out of executor
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/pipeline.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#299 Fixup image buffer dump
  samples/ppm.cc
  src/vulkan/engine_vulkan.cc
Labels: bug

#300 Fixup sample app buffer parsing
  samples/amber.cc
  src/descriptor_set_and_binding_parser.cc
  src/descriptor_set_and_binding_parser_test.cc
  src/tokenizer.cc
  third_party/CMakeLists.txt
Labels: bug

#303 Add -ps option to allow compiling shaders.
  include/amber/amber.h
  samples/amber.cc
  src/amber.cc
  src/executor.cc
  src/executor.h
  src/executor_test.cc
Labels: enhancement

#306 Add sample example.
  README.md
Labels: documentation

#304 Differentiate between instance and device extensions.
  include/amber/amber_vulkan.h
  include/amber/recipe.h
  samples/amber.cc
  samples/config_helper.cc
  samples/config_helper.h
  samples/config_helper_dawn.cc
  samples/config_helper_dawn.h
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor_test.cc
  src/recipe.cc
  src/script.cc
  src/script.h
  src/script_test.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: enhancement

#308 Allow querying vkGetPhysicalProperties2
  include/amber/amber_vulkan.h
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  tests/cases/clear.amber
Labels: enhancement

#305 Convert PushConstant to use a vector.
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
Labels: bug

#309 Hold required features as strings.
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor_test.cc
  src/feature.h
  src/script.cc
  src/script.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#312 Fixup shadow variable
  src/vulkan/device.cc
  src/vulkan/device.h
Labels: bug

#307 Flip the sample app to be less quiet.
  samples/amber.cc
  tests/run_tests.py
Labels: enhancement

#313 Allow specifiying variable pointers in requirements.
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/device.cc
Labels: enhancement

#315 Add fbsize require setting
  docs/vk_script.md
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  tests/cases/draw_rectangles.amber
Labels: enhancement

#316 Output requested images/buffers on probe failure.
  samples/amber.cc
  src/amber.cc
  src/executor.cc
  src/vulkan/engine_vulkan.cc
Labels: enhancement

#310 [vulkan] Code cleanup
  src/vulkan/buffer.cc
  src/vulkan/buffer.h
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/command_buffer.cc
  src/vulkan/command_buffer.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/compute_pipeline.h
  src/vulkan/descriptor.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/image.cc
  src/vulkan/image.h
  src/vulkan/index_buffer.cc
  src/vulkan/index_buffer.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#317 [vulkan] Don't store pipeline_layout or pipeline.
  src/vulkan/compute_pipeline.cc
  src/vulkan/compute_pipeline.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
Labels: refactoring
