Repository google/amber, pull requests merged in 2019-09, with the labels that each got.

#624 Allow recipe to change fence timeout.
  include/amber/recipe.h
  samples/amber.cc
  src/engine.h
  src/executor_test.cc
  src/recipe.cc
  src/script.h
Labels: enhancement

#635 Update clspv version
  CMakeLists.txt
  DEPS
  kokoro/scripts/linux/build.sh
  third_party/CMakeLists.txt
Labels: infra

#643 Roll some DEPS
  DEPS
Labels: infra

#644 Make script docs more visible in README
  README.md
Labels: documentation

#650 Roll Vulkan headers and loader to v1.1.114
  DEPS
  kokoro/scripts/macos/build.sh
  kokoro/scripts/windows/build.bat
  src/vulkan/find_vulkan.cmake
Labels: deps

#636 Add support for dumping multiple frame buffers.
  samples/amber.cc
Labels: enhancement

#651 Add validation layers to local build.
  .gitignore
  CMakeLists.txt
  DEPS
  kokoro/android/build.sh
  kokoro/scripts/linux/build.sh
  kokoro/scripts/linux/build_dawn.sh
  setup_debug_local.env
  third_party/CMakeLists.txt
Labels: deps, infra

#652 Suppress CLSPV tests
  tests/run_tests.py
Labels: bug

#653 Clear all colour buffers in Vulkan engine.
  src/vulkan/graphics_pipeline.cc
  tests/cases/clear_multiple.amber
Labels: bug

#654 Rename Buffer::GetTexelStride to Buffer::GetElementStide.
  src/amber.cc
  src/buffer.h
  src/dawn/engine_dawn.cc
  src/executor.cc
Labels: refactoring

#656 [dawn] fix build
  kokoro/scripts/linux/build_dawn.sh
Labels: kokoro:run

#655 Rename Buffer::ResizeTo to Buffer::SetSizeInElements.
  src/buffer.cc
  src/buffer.h
  src/pipeline.cc
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/pipeline.cc
Labels: refactoring

#658 Create Format directly instead of going through DatumType.
  src/pipeline.cc
  src/vkscript/command_parser.cc
  src/vkscript/parser.cc
Labels: refactoring

#657 [AmberScript] Fix parsing of matrix data into buffers.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/buffer.cc
  src/pipeline.cc
  src/vulkan/buffer_descriptor.cc
  tests/cases/matrix_initialization.amber
Labels: bug

#662 Remove stale forward declarations
  src/format_parser.h
  src/vulkan/buffer_descriptor.h
  src/vulkan/resource.h
Labels: refactoring

#661 Use Format for args instead of DatumType.
  src/amberscript/parser.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
Labels: refactoring

#663 Cleanup DatumType methods.
  src/datum_type.cc
  src/datum_type.h
Labels: refactoring

#664 Remove DatumType usage from AmberScript parser.
  Android.mk
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/buffer.h
  src/format_parser.cc
  src/format_parser.h
  src/vkscript/command_parser.h
  src/vkscript/datum_type.cc
  src/vkscript/datum_type.h
  src/vkscript/datum_type_parser.h
  src/vkscript/datum_type_test.cc
Labels: refactoring

#667 Remove DatumType.
  Android.mk
  src/CMakeLists.txt
  src/buffer.h
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  src/vkscript/datum_type.cc
  src/vkscript/datum_type.h
  src/vkscript/datum_type_parser.cc
  src/vkscript/datum_type_parser.h
  src/vkscript/datum_type_parser_test.cc
  src/vkscript/datum_type_test.cc
Labels: refactoring

#669 Add segments to format class
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/format.cc
  src/format.h
  src/format_parser_test.cc
  src/format_test.cc
  src/verifier.cc
  src/verifier_test.cc
  src/vkscript/datum_type_parser.cc
  src/vkscript/datum_type_parser_test.cc
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
Labels: refactoring

#670 Use enum for available layouts.
  src/buffer_test.cc
  src/format.cc
  src/format.h
  src/format_test.cc
  src/vkscript/command_parser.cc
Labels: refactoring

#671 [AmberScript] Add STD140 and STD430 layout modifiers to BUFFER.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/format.h
  tests/cases/matrices_uniform_draw.amber
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: amberscript, enhancement

#674 Remove GetComponents from the Format class.
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/format.cc
  src/format.h
  src/format_parser_test.cc
  src/format_test.cc
  src/verifier.cc
  src/vkscript/datum_type_parser.cc
  src/vkscript/datum_type_parser_test.cc
  src/vkscript/parser_test.cc
Labels: refactoring

#675 Use FormatParser where possible.
  src/amberscript/parser.cc
  src/format_test.cc
  src/pipeline.cc
  src/pipeline_test.cc
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/datum_type_parser.cc
  src/vkscript/parser.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#673 Added standalone tool for doing image comparison.
  samples/CMakeLists.txt
  samples/image_diff.cc
  src/buffer.cc
Labels: enhancement

#677 Store formats in pipeline and scripts.
  samples/image_diff.cc
  src/amberscript/parser.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/command.h
  src/format.cc
  src/format.h
  src/format_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
  src/script.h
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/parser.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring
