Repository google/amber, pull requests merged in 2019-03, with the labels that each got.

#329 Force RGBA color type for PNG output
  samples/png.cc
Labels: kokoro:run

#326 Add vulkan information into -V output.
  samples/amber.cc
  samples/config_helper.cc
  samples/config_helper.h
  samples/config_helper_dawn.cc
  samples/config_helper_dawn.h
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
Labels: enhancement

#322 Fixup version dump script.
  tools/update_build_version.py
Labels: bug

#321 Add Amber::AreAllRequirementsSupported
  include/amber/amber.h
  src/amber.cc
  src/tests
Labels: enhancement

#328 [vulkan] Generate wrapper functions for vulkan methods.
  .gitignore
  DEPS
  kokoro/ndk-build/build.sh
  samples/CMakeLists.txt
  src/CMakeLists.txt
  src/vulkan/CMakeLists.txt
  src/vulkan/device.cc
  src/vulkan/device.h
  tools/update_vk_wrappers.py
Labels: enhancement

#332 Rename vkscript test files.
  README.md
  tests/cases/clear.vkscript
  tests/cases/clear_and_probe_all_wrong_color.expect_fail.vkscript
  tests/cases/clear_and_probe_small_wrong_color.expect_fail.vkscript
  tests/cases/clear_and_probe_too_large_rect.expect_fail.vkscript
  tests/cases/clear_color.vkscript
  tests/cases/clear_color_with_probe_point.vkscript
  tests/cases/clear_color_without_clear_command.expect_fail.vkscript
  tests/cases/clear_color_without_probe.vkscript
  tests/cases/compute_accumulated_ubo_definition.vkscript
  tests/cases/compute_mat2x2.vkscript
  tests/cases/compute_mat2x3.vkscript
  tests/cases/compute_mat3x2.vkscript
  tests/cases/compute_mat3x3.vkscript
  tests/cases/compute_mat3x4.vkscript
  tests/cases/compute_mat4x3.vkscript
  tests/cases/compute_nothing.vkscript
  tests/cases/compute_nothing_with_ssbo.vkscript
  tests/cases/compute_probe_mat3.vkscript
  tests/cases/compute_push_const_mat2x2.vkscript
  tests/cases/compute_push_const_mat2x3.vkscript
  tests/cases/compute_push_const_mat3x2.vkscript
  tests/cases/compute_push_const_mat3x3.vkscript
  tests/cases/compute_push_const_mat3x4.vkscript
  tests/cases/compute_push_const_mat4x3.vkscript
  tests/cases/compute_push_constant_and_ssbo.vkscript
  tests/cases/compute_ssbo.vkscript
  tests/cases/compute_ssbo_with_entrypoint_command.vkscript
  tests/cases/compute_ssbo_with_tolerance.vkscript
  tests/cases/compute_ssbo_without_probe.vkscript
  tests/cases/compute_ubo_and_ssbo.vkscript
  tests/cases/draw_array_after_draw_rect.vkscript
  tests/cases/draw_rect_after_draw_array.vkscript
  tests/cases/draw_rect_and_draw_array_mixed.vkscript
  tests/cases/draw_rectangles.vkscript
  tests/cases/draw_rectangles_once.vkscript
  tests/cases/draw_rectangles_without_probe.vkscript
  tests/cases/draw_triangle_list.vkscript
  tests/cases/draw_triangle_list_in_r16g16b16a16_snorm_color_frame.vkscript
  tests/cases/draw_triangle_list_in_r16g16b16a16_uint_color_frame.vkscript
  tests/cases/draw_triangle_list_in_r32g32b32a32_sfloat_color_frame.vkscript
  tests/cases/draw_triangle_list_in_r8g8b8a8_snorm_color_frame.vkscript
  tests/cases/draw_triangle_list_in_r8g8b8a8_srgb_color_frame.vkscript
  tests/cases/draw_triangle_list_using_geom_shader.vkscript
  tests/cases/draw_triangle_list_using_tessellation.vkscript
  tests/cases/draw_triangle_list_with_depth.vkscript
  tests/cases/draw_triangle_list_with_index_buffer.vkscript
  tests/cases/draw_triangle_list_with_index_buffer_and_vertex_offset.vkscript
  tests/cases/draw_triangle_list_with_probe_point.vkscript
  tests/cases/draw_triangle_list_without_probe.vkscript
  tests/cases/multiple_clear_color.vkscript
  tests/cases/multiple_ssbo_update_with_graphics_pipeline.vkscript
  tests/cases/multiple_ssbo_with_sparse_descriptor_set_in_compute_pipeline.vkscript
  tests/cases/multiple_ubo_update_with_graphics_pipeline.vkscript
  tests/cases/probe_no_compute_with_multiple_ssbo_commands.vkscript
  tests/cases/probe_no_compute_with_ssbo.vkscript
  tests/cases/probe_without_clear_command.expect_fail.vkscript
  tests/cases/ssbo_with_graphics_pipeline.vkscript
  tests/run_tests.py
Labels: refactoring

#331 Allow multiple pipelines to execute.
  src/amber.cc
  src/command.cc
  src/command.h
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  src/vkscript/command_parser_test.cc
  src/vkscript/parser.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: enhancement

#338 [vulkan] fix shadow variable
  src/vulkan/engine_vulkan.cc
Labels: bug

#335 [amberscript] Implement RUN for compute and DRAW_RECT.
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/pipeline.h
  src/script.h
Labels: enhancement

#337 [vulkan] Remove SetBuffer.
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#339 Parse CLEAR command
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
Labels: enhancement

#319 Build with local vulkan data if requested
  .gitignore
  CMakeLists.txt
  DEPS
  kokoro/scripts/linux/build.sh
  kokoro/scripts/macos/build.sh
  kokoro/scripts/windows/build.bat
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
  src/vulkan/device.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/find_vulkan.cmake
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer_test.cc
  third_party/CMakeLists.txt
Labels: enhancement, infra

#340 [vulkan] Support multiple colour attachments.
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/pipeline.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
Labels: enhancement

#334 Add Delegate class to enable hooking log function around graphics API calls
  include/amber/amber.h
  samples/CMakeLists.txt
  samples/amber.cc
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor_test.cc
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  tools/update_vk_wrappers.py
Labels: enhancement

#341 Force cmake settings into the cache.
  third_party/CMakeLists.txt
Labels: infra

#354 Use template for Vulkan wrappers generation
  tools/update_vk_wrappers.py
Labels: refactoring

#353 [vulkan] Set correct colour attachment locations.
  src/vulkan/frame_buffer.cc
Labels: bug

#355 Correctly store BufferType in buffer.
  src/amberscript/parser.cc
  src/amberscript/parser_test.cc
  src/buffer.h
  src/buffer_data.h
  src/pipeline.cc
  src/pipeline.h
  src/vulkan/engine_vulkan.cc
Labels: refactoring

#356 Add buffer to probe command.
  src/amber.cc
  src/command.cc
  src/command.h
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#357 Store framebuffer info into buffers.
  src/amber.cc
  src/amberscript/parser.cc
  src/buffer.h
  src/datum_type.cc
  src/datum_type.h
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/vulkan/buffer_descriptor.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/frame_buffer.cc
Labels: refactoring

#358 Remove GetDescriptorInfo and store in Buffer object.
  src/amber.cc
  src/buffer.h
  src/command.h
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/verifier.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  src/vkscript/command_parser_test.cc
  src/vkscript/parser.cc
  src/vulkan/buffer.cc
  src/vulkan/buffer.h
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/descriptor.cc
  src/vulkan/descriptor.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/index_buffer.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
  src/vulkan/vertex_buffer_test.cc
  tests/cases/probe_no_compute_with_ssbo.vkscript
Labels: refactoring

#359 Rename vulkan/buffer to vulkan/transfer_buffer.
  Android.mk
  src/vulkan/CMakeLists.txt
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/index_buffer.cc
  src/vulkan/index_buffer.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#360 Remove unused method.
  src/vulkan/engine_vulkan.cc
  src/vulkan/frame_buffer.h
Labels: refactoring

#361 Rename vulkan/image to vulkan/transfer_image
  Android.mk
  src/vulkan/CMakeLists.txt
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
Labels: refactoring

#363 Simplify vulkan/resource classes.
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#364 [vulkan] Unhook push_constant from resource.
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
Labels: refactoring

#365 Remove unused descriptor code
  src/vulkan/buffer_descriptor.h
  src/vulkan/descriptor.cc
  src/vulkan/descriptor.h
Labels: refactoring

#366 [vulkan] remove Shutdown methods.
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/command_buffer.cc
  src/vulkan/command_buffer.h
  src/vulkan/command_pool.cc
  src/vulkan/command_pool.h
  src/vulkan/descriptor.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/index_buffer.cc
  src/vulkan/index_buffer.h
  src/vulkan/pipeline.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
Labels: refactoring

#367 [AmberScript] Implement EXPECT EQ_RGB(A)? parsing
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  tests/cases/clear.amber
Labels: enhancement

#373 [testing] Add suppressions to test runner
  tests/run_tests.py
Labels: enhancement

#374 Change depth format for test.
  tests/cases/draw_triangle_list_with_depth.vkscript
Labels: bug

#375 [vulkan] Add missing result check
  src/vulkan/graphics_pipeline.cc
Labels: bug

#376 Guard against missing framebuffer pointer
  src/vulkan/engine_vulkan.cc
  src/vulkan/transfer_image.cc
Labels: enhancement

#372 [vulkan] Better error message when failing to make vulkan device.
  samples/config_helper_vulkan.cc
Labels: enhancement

#377 Remove pipeline from probe commands.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_test.cc
  src/command.cc
  src/command.h
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vulkan/compute_pipeline.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/pipeline.h
  tests/cases/clear.amber
Labels: refactoring

#381 Enable find vulkan on Android
  CMakeLists.txt
Labels: infra

#380 Add a PipelineCommand class.
  src/command.cc
  src/command.h
Labels: refactoring

#378 [vulkan] More MoltenVK suppressions
  tests/run_tests.py
Labels: bug

#382 [vulkan] Wrap render pass into RAII object.
  src/vulkan/command_buffer.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/index_buffer.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/resource.cc
  src/vulkan/transfer_image.cc
  src/vulkan/vertex_buffer.cc
Labels: refactoring

#384 [vulkan] Merge CommandBuffer End and SubmitAndReset.
  src/vulkan/command_buffer.cc
  src/vulkan/command_buffer.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/pipeline.cc
Labels: refactoring

#385 [vulkan] Remove redundant record and submit commands.
  src/vulkan/compute_pipeline.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
Labels: refactoring

#386 [vulkan] Add CommandBuffer guard.
  src/vulkan/command_buffer.cc
  src/vulkan/command_buffer.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/pipeline.cc
Labels: refactoring

#387 [vulkan] Rename methods returning vulkan objects.
  src/vulkan/command_buffer.cc
  src/vulkan/command_pool.cc
  src/vulkan/command_pool.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/descriptor.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_image.cc
  src/vulkan/vertex_buffer.h
Labels: refactoring

#383 [vulkan] Fixup width of draw commands.
  src/amberscript/parser.cc
  src/amberscript/parser_test.cc
  src/verifier.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/pipeline.cc
  tests/cases/draw_rect.amber
  tests/cases/draw_rect.vkscript
  tests/cases/draw_rect_and_ortho.vkscript
  tests/cases/draw_rect_orth.vkscript
Labels: bug

#390 [vulkan] Change vulkan generation location.
  src/vulkan/device.cc
  src/vulkan/device.h
  tools/update_vk_wrappers.py
Labels: bug, infra

#389 [vulkan] Move GetFrameBuffer out of engine code.
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#391 Move config helper to use destructor
  samples/amber.cc
  samples/config_helper.cc
  samples/config_helper.h
  samples/config_helper_dawn.cc
  samples/config_helper_dawn.h
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
Labels: refactoring

#393 Add missing iterator include.
  samples/config_helper_vulkan.cc
Labels: infra

#399 Initialize comparator.
  src/vkscript/command_parser.cc
Labels: bug

#400 Remove unreachable line
  src/vulkan/pipeline.cc
Labels: bug

#401 Make python required
  README.md
Labels: documentation

#403 Change cmake to use PYTHON_EXECUTABLE.
  samples/CMakeLists.txt
  src/vulkan/CMakeLists.txt
Labels: infra

#406 Remove return as it's unreachable.
  src/vulkan/pipeline.cc
Labels: bug

#394 Convert buffer data earlier
  src/amberscript/parser_test.cc
  src/buffer.cc
  src/buffer.h
  src/vkscript/command_parser.cc
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/index_buffer.cc
  src/vulkan/index_buffer.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#396 Move engine shutdown to destructor
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#409 [vulkan] Move pipeline shutdown to destructor
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
Labels: refactoring

#407 [vulkan] Remove memory pointer from Buffer.
  src/amber.cc
  src/buffer.h
  src/executor.cc
  src/vulkan/buffer_descriptor.cc
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
Labels: refactoring

#408 Initialize amber structures.
  include/amber/amber.h
  samples/amber.cc
  src/amber.cc
Labels: refactoring

#410 [vulkan] merge Descriptor and BufferDescriptor.
  Android.mk
  src/vulkan/CMakeLists.txt
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/descriptor.cc
  src/vulkan/descriptor.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
Labels: refactoring

#412 [vulkan] remove unnecessary Result returns.
  src/vulkan/buffer_descriptor.cc
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/index_buffer.cc
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#411 Add EXPECT EQ
  docs/amber_script.md
  src/amber.cc
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/executor.cc
  tests/cases/expect_eq.amber
Labels: refactoring

#413 [vulkan] Cleanup device methods for properties
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/compute_pipeline.h
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/index_buffer.cc
  src/vulkan/index_buffer.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#414 [vulkan] Remove params which can be retrieved from Device.
  src/vulkan/command_buffer.cc
  src/vulkan/command_buffer.h
  src/vulkan/command_pool.cc
  src/vulkan/command_pool.h
  src/vulkan/compute_pipeline.cc
  src/vulkan/compute_pipeline.h
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
Labels: refactoring

#415 [vulkan] Remove vulkan/format_data
  Android.mk
  src/format.cc
  src/format.h
  src/vulkan/CMakeLists.txt
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/format_data.cc
  src/vulkan/format_data.h
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
  src/vulkan/index_buffer.cc
  src/vulkan/resource.cc
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#424 [vulkan] remove un-needed methods
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
Labels: refactoring

#419 Remove buffer_data file.
  src/buffer.h
  src/buffer_data.h
  src/engine.h
  src/vulkan/device.cc
  src/vulkan/device.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.h
Labels: refactoring

#420 Hide pipeline buffer formats
  samples/amber.cc
  src/amber.cc
  src/pipeline.cc
  src/pipeline.h
  src/vkscript/parser.cc
Labels: refactoring

#432 [amberscript] split parser test file
  src/CMakeLists.txt
  src/amberscript/parser_attach_test.cc
  src/amberscript/parser_bind_test.cc
  src/amberscript/parser_buffer_test.cc
  src/amberscript/parser_clear_color_test.cc
  src/amberscript/parser_clear_test.cc
  src/amberscript/parser_copy_test.cc
  src/amberscript/parser_expect_test.cc
  src/amberscript/parser_framebuffer_test.cc
  src/amberscript/parser_pipeline_test.cc
  src/amberscript/parser_run_test.cc
  src/amberscript/parser_shader_opt_test.cc
  src/amberscript/parser_shader_test.cc
  src/amberscript/parser_test.cc
Labels: refactoring

#434 [amberscript] add DEVICE_FEATURE.
  docs/amber_script.md
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_device_feature_test.cc
  src/script.cc
  src/script.h
  src/vkscript/parser.cc
  tests/cases/draw_rectangles.amber
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: enhancement

#421 [vkscript] report error on invalid ssbo subdata offset.
  docs/vk_script.md
  src/datum_type.cc
  src/datum_type.h
  src/verifier.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
Labels: bug

#437 Remove accidentally added file
  tests/cases/draw_rectangles.amber
Labels: bug
