Repository google/amber, pull requests merged in 2019-01, with the labels that each got.

#187 Vulkan: fix validation errors
  src/vulkan/buffer.cc
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/device.cc
  src/vulkan/graphics_pipeline.cc
  tests/cases/compute_in_spirv_generated_by_clspv.amber
Labels: bug

#211 Fix: incorrect probe region bug
  src/verifier.cc
  src/verifier_test.cc
Labels: bug

#215 Lower cmake version for CTS compatibility
  CMakeLists.txt
Labels: infra

#218 Convert API to C++03 from C++11 for CTS compatibility
  include/amber/amber.h
  include/amber/amber_vulkan.h
  include/amber/recipe.h
  include/amber/shader_info.h
  samples/amber.cc
  samples/config_helper.cc
  src/amber.cc
  src/amberscript/parser.cc
  src/amberscript/parser_test.cc
  src/command.h
  src/dawn/engine_dawn.cc
  src/engine.cc
  src/executor.cc
  src/executor_test.cc
  src/pipeline.cc
  src/pipeline_test.cc
  src/recipe.cc
  src/script_test.cc
  src/shader_compiler.cc
  src/shader_compiler_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vkscript/section_parser.cc
  src/vkscript/section_parser_test.cc
  src/vulkan/engine_vulkan.cc
Labels: refactoring

#223 Print line number of failing probe command.
  src/command.h
  src/verifier.cc
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/parser.cc
Labels: enhancement

#235 Dawn: fix compile errors on newer Dawn
  src/dawn/engine_dawn.cc
Labels: bug

#234 Update vulkan readme notes
  README.md
Labels: documentation

#243 Consolidate Initialize methods in Engine.
  src/amber.cc
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
Labels: refactoring

#244 [amberscript] Buffer parsing updates.
  Android.mk
  docs/amber_script.md
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_data.h
  src/format_parser.cc
  src/format_parser.h
  src/format_parser_test.cc
  src/vkscript/parser.cc
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: enhancement

#250 Fixup ENTRY_POINT processing for AmberScript
  include/amber/shader_info.h
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
  src/script.cc
  src/vulkan/engine_vulkan.cc
Labels: enhancement

#252 [amberscript] Parse FRAMEBUFFER_SIZE
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_test.cc
  src/pipeline.h
Labels: enhancement
