Repository google/amber, pull requests merged in 2019-07, with the labels that each got.

#572 [vulkan] Fixup colour attachment setup for render pass.
  src/vulkan/graphics_pipeline.cc
  src/vulkan/graphics_pipeline.h
Labels: bug

#586 Add clspv kokoro bot config
  kokoro/linux-gcc-release-clspv/build.sh
  kokoro/linux-gcc-release-clspv/continuous.cfg
  kokoro/linux-gcc-release-clspv/presubmit.cfg
  kokoro/scripts/linux/build.sh
Labels: infra

#588 Kokoro bot requires older toolchain
  third_party/CMakeLists.txt
Labels: infra

#595 Add support for "NaN" as a double value
  src/tokenizer.cc
  src/tokenizer_test.cc
Labels: enhancement
