Repository google/amber, pull requests merged in 2019-10, with the labels that each got.

#680 Initialize data buffer.
  src/buffer.cc
Labels: bug

#679 New type structure
  Android.mk
  docs/memory_layout.md
  samples/image_diff.cc
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/format.cc
  src/format.h
  src/format_data.h
  src/format_parser.h
  src/format_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
  src/script.h
  src/type.cc
  src/type.h
  src/type_parser.cc
  src/type_parser.h
  src/type_parser_test.cc
  src/type_test.cc
  src/verifier.cc
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vkscript/datum_type_parser.cc
  src/vkscript/datum_type_parser.h
  src/vkscript/datum_type_parser_test.cc
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#687 Fixup Dawn engine due to upstream changes
  src/dawn/engine_dawn.cc
Labels: deps

#688 [AmberScript] Adding struct support
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_attach_test.cc
  src/amberscript/parser_buffer_test.cc
  src/amberscript/parser_expect_test.cc
  src/amberscript/parser_struct_test.cc
  src/buffer.cc
  src/format.cc
  src/script.cc
  src/script.h
  src/script_test.cc
  src/type.h
  tests/cases/struct.amber
  tests/cases/struct_compare.amber
  tests/cases/struct_embedded.amber
  tests/cases/struct_embedded_padded_430.amber
Labels: amberscript, enhancement

#689 Added EMD histogram comparison support.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_attach_test.cc
  src/amberscript/parser_expect_test.cc
  src/buffer.cc
  src/buffer.h
  src/command.h
  src/executor.cc
  tests/cases/buffer_emd.amber
Labels: enhancement

#695 Fixed warnings seen when compiling inside dEQP.
  kokoro/scripts/windows/build.bat
  src/verifier.cc
Labels: kokoro:run

#702 Define clear colour default in amberscript.md.
  docs/amber_script.md
Labels: documentation

#696 Specify comparison parameters after comparison algorithm
  samples/image_diff.cc
Labels: enhancement
