Repository google/amber, pull requests merged in 2019-05, with the labels that each got.

#495 [vkscript] Store push constant data in a buffer.
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
Labels: refactoring

#500 Update VkScript buffer document.
  docs/vk_script.md
Labels: bug, documentation

#502 [VkScript] Add pipeline validation.
  src/executor_test.cc
  src/pipeline.cc
  src/pipeline_test.cc
  src/vkscript/parser.cc
  src/vkscript/parser.h
  src/vkscript/parser_test.cc
  tests/cases/buffer_without_format.expect_fail.vkscript
Labels: bug

#498 Add support for DoDrawRect in dawn backend
  kokoro/scripts/linux/build_dawn.sh
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
Labels: enhancement

#507 Allow setting name of framebuffer to extract.
  include/amber/amber.h
  samples/amber.cc
  src/amber.cc
Labels: enhancement

#506 Only resize buffer if it will become bigger.
  src/buffer.cc
  src/buffer_test.cc
  tests/cases/ssbo_subdata_size.vkscript
Labels: bug

#504 [vkscript] Document buffer format restriction.
  docs/vk_script.md
Labels: documentation

#517 [amberscript] Add TOLERANCE parsing.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_expect_test.cc
  tests/cases/compute_ssbo_with_tolerance.amber
Labels: enhancement

#514 [vkscript] Set default format into buffers.
  docs/vk_script.md
  src/buffer.h
  src/vkscript/command_parser.cc
  tests/cases/scratch_ssbo.vkscript
Labels: enhancement

#512 Add support for building SwiftShader
  .gitignore
  CMakeLists.txt
  DEPS
  README.md
  src/vulkan/find_vulkan.cmake
  third_party/CMakeLists.txt
Labels: enhancement

#521 Simplify build settings
  CMakeLists.txt
  third_party/CMakeLists.txt
Labels: infra, refactoring

#511 Add HLSL support through DXC
  .gitignore
  CMakeLists.txt
  DEPS
  README.md
  include/amber/shader_info.h
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/dxc_helper.cc
  src/dxc_helper.h
  src/shader_compiler.cc
  src/shader_compiler.h
  tests/cases/draw_triangle_list_hlsl.amber
  tests/run_tests.py
  third_party/CMakeLists.txt
Labels: enhancement

#530 Remove old location code from buffer class.
  src/buffer.h
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
Labels: refactoring

#535 Add missing file close
  samples/amber.cc
Labels: bug
