Repository google/amber, pull requests merged in 2019-04, with the labels that each got.

#438 [vulkan] Use LOAD_OP_LOAD for the default attachment description
  src/vulkan/graphics_pipeline.cc
  tests/cases/clear_partial_overwrite.vkscript
Labels: bug

#439 [amberscript] Allow buffer data on same line as declaration.
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
Labels: enhancement

#441 [vulkan] simplify image transition code.
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
Labels: refactoring

#442 Add amber overview doc
  docs/amber.md
Labels: documentation

#443 [amberscript] Add REPEAT command
  docs/amber_script.md
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_repeat_test.cc
  src/command.cc
  src/command.h
  src/executor.cc
  src/executor.h
  src/script.h
  src/vkscript/command_parser.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  tests/cases/repeat.amber
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: enhancement

#445 [vulkan] TransferImage knows current layout and stage
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
Labels: refactoring

#448 Generate a Format from a DataBuffer.
  src/CMakeLists.txt
  src/datum_type.cc
  src/datum_type.h
  src/datum_type_test.cc
Labels: enhancement

#449 [vulkan] Add a write framebuffer state; cleanup
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.cc
  src/vulkan/transfer_image.cc
Labels: refactoring

#452 [vulkan] copy fb data onto device
  src/vulkan/frame_buffer.cc
  src/vulkan/frame_buffer.h
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vk-funcs.inc
Labels: bug

#453 [AmberScript] Add DERIVE_PIPELINE
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_bind_test.cc
  src/amberscript/parser_buffer_test.cc
  src/amberscript/parser_pipeline_test.cc
  src/pipeline.cc
  src/pipeline.h
  src/pipeline_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/parser.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/graphics_pipeline.cc
  tests/cases/draw_rectangles.amber
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: enhancement

#450 [vulkan] Allow setting vertex buffer with a data buffer
  src/buffer.h
  src/datum_type.cc
  src/datum_type.h
  src/datum_type_test.cc
  src/executor.cc
  src/format_parser.cc
  src/verifier_test.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/vertex_buffer.cc
  src/vulkan/vertex_buffer.h
Labels: bug

#457 Simplify Format::GetBytesize; rename to SizeInBytes
  samples/amber.cc
  samples/config_helper_dawn.cc
  samples/config_helper_vulkan.cc
  src/amberscript/parser_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/command_data_test.cc
  src/datum_type_test.cc
  src/dawn/pipeline_info_test.cc
  src/executor_test.cc
  src/format.cc
  src/format.h
  src/format_parser_test.cc
  src/result_test.cc
  src/shader_compiler_test.cc
  src/tokenizer_test.cc
  src/verifier_test.cc
  src/vkscript/command_parser_test.cc
  src/vkscript/datum_type_parser_test.cc
  src/vkscript/parser_test.cc
  src/vkscript/section_parser_test.cc
  src/vulkan/transfer_image.cc
  src/vulkan/vertex_buffer.cc
Labels: refactoring

#458 Add Buffer::GetFormat
  src/amber.cc
  src/amberscript/parser_bind_test.cc
  src/amberscript/parser_buffer_test.cc
  src/amberscript/parser_pipeline_test.cc
  src/buffer.h
  src/datum_type.cc
  src/datum_type.h
  src/datum_type_test.cc
  src/executor.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/frame_buffer.cc
  src/vulkan/graphics_pipeline.cc
  src/vulkan/vertex_buffer.cc
Labels: refactoring

#459 AmberScript and README updates
  README.md
  docs/amber_script.md
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: documentation

#460 Use Format instead of DatumType where possible.
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_buffer_test.cc
  src/buffer.cc
  src/buffer.h
  src/datum_type.cc
  src/format.cc
  src/format.h
  src/vkscript/parser_test.cc
Labels: refactoring

#461 Move Format up into base Buffer class
  src/buffer.h
  src/format.cc
  src/verifier.cc
  src/verifier_test.cc
Labels: refactoring

#462 Convert BufferCommand to use Format.
  src/command.h
  src/datum_type.cc
  src/format.cc
  src/format.h
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  src/vkscript/command_parser_test.cc
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/pipeline.cc
  src/vulkan/push_constant.cc
  src/vulkan/resource.cc
  src/vulkan/resource.h
Labels: refactoring

#463 Add doc/engines.md
  docs/engines.md
Labels: documentation

#464 Convert ProbeSSBO to use Format objects.
  src/amberscript/parser.cc
  src/amberscript/parser_expect_test.cc
  src/command.h
  src/verifier.cc
  src/verifier_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser_test.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/resource.h
Labels: refactoring

#466 Merge Data and Format buffers.
  src/CMakeLists.txt
  src/amber.cc
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_bind_test.cc
  src/amberscript/parser_buffer_test.cc
  src/amberscript/parser_pipeline_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/executor.cc
  src/format.cc
  src/format.h
  src/format_test.cc
  src/pipeline.cc
  src/pipeline_test.cc
  src/script_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/parser.cc
  src/vkscript/parser_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/vertex_buffer_test.cc
Labels: refactoring

#467 Adding depth and stencil to DoClear
  src/dawn/engine_dawn.cc
  src/dawn/pipeline_info.h
  tests/cases/clear_with_depth.amber
Labels: enhancement

#471 Add compute tests for AmberScript.
  tests/cases/compute_accumulated_ubo_definition.amber
  tests/cases/compute_mat2x2.amber
Labels: enhancement

#472 [amberscript] Add DRAW_ARRAYS command
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/amberscript/parser_run_test.cc
  tests/cases/draw_triangle_list.amber
Labels: enhancement

#476 Flush out some class/method documentation.
  Doxyfile
  docs/vulkan_resource_and_descriptor.md
  include/amber/amber.h
  include/amber/shader_info.h
  include/amber/value.h
  samples/config_helper.h
  samples/config_helper_dawn.cc
  samples/config_helper_dawn.h
  samples/config_helper_vulkan.h
  samples/dawn_device_metal.h
  samples/log.h
  src/amberscript/parser.h
  src/buffer.h
  src/command.h
  src/datum_type.h
  src/dawn/engine_dawn.h
  src/dawn/pipeline_info.h
  src/engine.h
  src/format.h
  src/format_parser.h
  src/pipeline.h
  src/pipeline_data.h
  src/shader.h
  src/shader_compiler.h
  src/sleep.h
  src/tokenizer.h
  src/vkscript/command_parser.h
  src/vkscript/datum_type_parser.h
  src/vkscript/parser.h
  src/vkscript/section_parser.h
  src/vulkan/buffer_descriptor.h
  src/vulkan/command_buffer.h
  src/vulkan/command_pool.h
  src/vulkan/compute_pipeline.h
  src/vulkan/device.h
  src/vulkan/engine_vulkan.h
  src/vulkan/frame_buffer.h
  src/vulkan/graphics_pipeline.h
  src/vulkan/index_buffer.h
  src/vulkan/pipeline.h
  src/vulkan/push_constant.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  src/vulkan/transfer_buffer.cc
  src/vulkan/transfer_buffer.h
  src/vulkan/transfer_image.cc
  src/vulkan/transfer_image.h
  src/vulkan/vertex_buffer.h
Labels: documentation

#478 Scripting document cleanups
  docs/amber_script.md
  docs/vk_script.md
  tools/amber-syntax.vim
  tools/amber.sublime-syntax
Labels: documentation

#479 Enable syntax highlighting in amberscript doc
  docs/amber_script.md
Labels: documentation

#482 Fix format sizes due to layout.
  src/amberscript/parser.cc
  src/amberscript/parser_buffer_test.cc
  src/buffer.cc
  src/buffer.h
  src/buffer_test.cc
  src/command.h
  src/datum_type.cc
  src/format.cc
  src/format.h
  src/format_test.cc
  src/verifier.cc
  src/vkscript/parser_test.cc
Labels: bug

#483 Add flag to log execute calls.
  include/amber/amber.h
  samples/amber.cc
  src/amber.cc
  src/command.h
  src/executor.cc
  src/executor.h
  src/executor_test.cc
Labels: enhancement

#484 Move buffer filling code into Buffer class.
  src/buffer.cc
  src/buffer.h
  src/command.h
  src/datum_type.cc
  src/format.cc
  src/format.h
  src/format_test.cc
  src/vkscript/command_parser.cc
  src/vkscript/command_parser.h
  src/vkscript/command_parser_test.cc
  src/vulkan/buffer_descriptor.cc
  src/vulkan/buffer_descriptor.h
  src/vulkan/pipeline.cc
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
  src/vulkan/resource.cc
  src/vulkan/resource.h
  tests/cases/compute_push_constant_and_ssbo.vkscript
  tests/cases/multiple_ubo_update_with_graphics_pipeline.vkscript
Labels: refactoring

#486 [amberscript] Add push_constant support.
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_bind_test.cc
  src/amberscript/parser_expect_test.cc
  src/buffer.cc
  src/buffer.h
  src/pipeline.cc
  src/pipeline.h
  src/vulkan/engine_vulkan.cc
  src/vulkan/pipeline.cc
  src/vulkan/pipeline.h
  src/vulkan/push_constant.cc
  src/vulkan/push_constant.h
  tests/cases/compute_push_constant_and_ssbo.amber
Labels: enhancement

#488 [vkscript] Skip adding uniform buffer to list of pipeline buffers
  src/vkscript/command_parser.cc
Labels: bug

#492 Add push constant graphics tests.
  samples/png.cc
  samples/ppm.cc
  samples/ppm.h
  tests/cases/graphics_push_constants.amber
  tests/cases/graphics_push_constants.vkscript
Labels: enhancement

#487 [amberscript] Extend DRAW_ARRAYS parsing.
  src/amberscript/parser.cc
  src/amberscript/parser_run_test.cc
Labels: enhancement

#490 [amberscript] Add ability to set engine data
  docs/amber_script.md
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_set_test.cc
Labels: enhancement

#493 [amberscript] Add instance and device extensions
  docs/amber_script.md
  src/CMakeLists.txt
  src/amberscript/parser.cc
  src/amberscript/parser.h
  src/amberscript/parser_extension_test.cc
  src/script.cc
  src/script.h
Labels: enhancement

#494 [amberscript] Add INDEXED parsing
  docs/amber_script.md
  src/amberscript/parser.cc
  src/amberscript/parser_run_test.cc
Labels: enhancement
