Repository google/amber, pull requests merged in 2020-02, with the labels that each got.

#788 CommandBuffer reset fixes.
  src/engine.h
  src/vulkan/command_buffer.cc
  src/vulkan/pipeline.h
  tests/run_tests.py
Labels: bug

#787 Rolling 14 dependencies
  DEPS
Labels: deps

#789 Rolling 7 dependencies
  DEPS
Labels: deps

#790 Rolling 7 dependencies
  DEPS
  samples/config_helper_vulkan.cc
Labels: deps

#792 Add support for 8-bit int shader/storage features
  docs/amber_script.md
  samples/config_helper_vulkan.cc
  samples/config_helper_vulkan.h
  src/amberscript/parser_device_feature_test.cc
  src/script.cc
  src/vulkan/device.cc
  tests/cases/int8.amber
  tests/run_tests.py
Labels: enhancement

#793 Switch to rsplit for repo path in git-sync-deps
  tools/git-sync-deps
Labels: enhancement, infra

#795 Enable swiftshader on MacOS Debug
  kokoro/macos-clang-debug/build.sh
Labels: infra

#791 Implement DRAW_GRID
  docs/amber_script.md
  docs/engines.md
  src/amberscript/parser.cc
  src/amberscript/parser_run_test.cc
  src/command.cc
  src/command.h
  src/dawn/engine_dawn.cc
  src/dawn/engine_dawn.h
  src/engine.h
  src/executor.cc
  src/executor_test.cc
  src/vulkan/engine_vulkan.cc
  src/vulkan/engine_vulkan.h
  tests/cases/draw_grid.amber
  tests/cases/draw_grid_multiple_color_attachment.amber
  tests/cases/draw_grid_multiple_pipeline.amber
  tests/cases/draw_grid_with_buffer.amber
  tests/cases/draw_grid_with_two_vertex_data_attached.expect_fail.amber
  tests/cases/draw_grids.amber
  tests/run_tests.py
  tools/amber.sublime-syntax
Labels: enhancement
